### PR TITLE
Revert "Use threads instead"

### PR DESCRIPTION
**Pull request by lvarin**
This reverts commit e212e2ba4df3d008855cd054bf7094996da35cd9.

### CODE REVIEW

**Review by joonas-somero — APPROVED** [review]

**Comment by rkronberg** [comment]
Not sure if related, but after this merge the preview build does not seem to be automatically triggered by changes pushed to a branch. @lvarin @joonas-somero

**Comment by lvarin** [comment]
Can you provide an example? Commit and branch, please

**Comment by rkronberg** [comment]
> Can you provide an example? Commit and branch, please

https://github.com/CSCfi/csc-user-guide/pull/2324/commits/0bb661ca0fc95f16cb659939ca3bd8292e481d6b

branch gromacs-2024.4

**Comment by lvarin** [comment]
Thanks for the example

Try again please. The issue does not seem to be related with this PR, but with the move from Rahti 1 to 2 and the change of the Hook's URL.

**Comment by rkronberg** [comment]
https://github.com/CSCfi/csc-user-guide/pull/2324/commits/66f9fe100c2e1166062dd6efb7cccce8156acfa8
Neither this one seems to be triggering a build.

**Pull request merged**
