### PR TITLE
Add Rasmus new plugins

### PR DESCRIPTION
**Pull request by lvarin**

### CODE REVIEW

**Review by rkronberg — APPROVED** [review]
LGTM, thanks!

**Comment by joonas-somero** [comment]
I'd like to take this opportunity to mention that the requirements differ quite a lot from what we have at production. I guess the diff is mostly stuff left over from when I revised the requirements last summer. Should we try to see what's not needed anymore?

**Comment by joonas-somero** [comment]
> Ahh fair point Joonas. Wouldn't a simple drop-in replacement by the current production requirements be enough? Or are there something that is specifically needed by the preview (but not docs.csc.fi)?

The requirements.txt lists two packages, namely `flask` and `GitPython`, that are used by the preview. I don't know which, if any,  packages under `# These are dependencies of the above` are explicitly for `flask`. `GitPython` has since been included in requirements.txt of production, under the same comment `# These are dependencies of the above`.

**Comment by lvarin** [comment]
IMHO the `requirements.txt` file should be the same in the 3(?) environments. A couple of extra installed libraries should not be a concern. And the upgrade path should be: `dev-repview` -> `prod-preview` -> `prod-prod` (<docs.csc.fi>), where we do not allow any change in `requirements.txt` going directly to <docs.csc.fi>. I think the advantages of this outweighs the downsides.

**Comment by joonas-somero** [comment]
> IMHO the `requirements.txt` file should be the same in the 3(?) environments. A couple of extra installed libraries should not be a concern. And the upgrade path should be: `dev-preview` -> `prod-preview` -> `prod-prod` (<docs.csc.fi>), where we do not allow any change in `requirements.txt` going directly to <docs.csc.fi>. I think the advantages of this outweighs the downsides.

Sounds good! Should we just merge this PR for now, though, so that we can preview the breadcrumbs navigation fixes?

**Comment by lvarin** [comment]
lgtm

**Review by joonas-somero — APPROVED** [review]

**Pull request merged**
